### ISSUE TITLE
Incorrect Handling of Local Image Paths 

### ISSUE THREAD

**Issue by zhildzik** [Nakanishi123/astro-rehype-img2pic#1]
https://github.com/Nakanishi123/astro-rehype-img2pic/blob/3d0f55b85661f2e51102adea650fb3f910c731f6/src/mdImgToPic.ts#L45

According to the comment in the code, non-local images (e.g., images hosted externally) should be skipped, while local images should be processed.

**Problem:** The plugin's logic incorrectly skips local images by checking if the image path does not start with "http".
**Expected Behavior:** The plugin should process local images (e.g., those starting with relative paths or located in the project directory) and skip only external images.

**Affected Code:**
`
// Current code
if (!node.properties.src.startsWith("http")) return; // This skips local images

// Suggested fix
if (node.properties.src.startsWith("http")) return; // This correctly skips external images
`

**Comment by Nakanishi123** [comment]
Thanks for the feedback🙏
